/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.mavenproject3;

import TDAs.TreeMap;
import java.awt.BorderLayout;
import java.io.IOException;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author garci
 */
public class Slice_Dice extends javax.swing.JFrame {
    private Buscador find ;
    private TreeMap map;
    
    
    
    /** Creates new form Slice_Dice */
    public Slice_Dice() {
        initComponents();
    }
    
    public Slice_Dice(Buscador find) throws IOException{
        //this();
        this.find=find;
        this.map=find.getT();
        Stage stage = new Stage();
        Parent root = FXMLLoader.load(getClass().getResource("Menu.fxml"));
        Scene scene = new Scene(root);
        stage = new Stage(StageStyle.DECORATED);
        stage.setScene(scene);
        stage.show();
        
        crearPanel(500, 660, "Directorio Principal", 800.00);
        
    }

    public Buscador getFind() {
        return find;
    }

    public void setFind(Buscador find) {
        this.find = find;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_nameFile = new javax.swing.JLabel();
        lbl_weight_File = new javax.swing.JLabel();
        jP2 = new javax.swing.JPanel();
        jlb_SC = new javax.swing.JLabel();
        btn_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl_nameFile.setText("Nombre_Archivo");

        lbl_weight_File.setText("Tamnio_Archivo");

        jP2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));

        javax.swing.GroupLayout jP2Layout = new javax.swing.GroupLayout(jP2);
        jP2.setLayout(jP2Layout);
        jP2Layout.setHorizontalGroup(
            jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        jP2Layout.setVerticalGroup(
            jP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_nameFile, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(lbl_weight_File))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nameFile)
                    .addComponent(lbl_weight_File))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jlb_SC.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlb_SC.setText("Slice&Dice");

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_regresar)
                        .addGap(273, 273, 273)
                        .addComponent(jlb_SC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlb_SC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_regresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void initComponents( javax.swing.JPanel jPanel1) {

        
        lbl_nameFile = new javax.swing.JLabel();
        lbl_weight_File = new javax.swing.JLabel();
        jP2 = new javax.swing.JPanel();
        jlb_SC = new javax.swing.JLabel();
        btn_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        

        jlb_SC.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlb_SC.setText("Slice&Dice");

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_regresar)
                        .addGap(273, 273, 273)
                        .addComponent(jlb_SC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlb_SC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_regresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    
    
    
    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Slice_Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Slice_Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Slice_Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Slice_Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Slice_Dice().setVisible(true);
            }
        });
    }
    public javax.swing.JPanel parciones(TreeMap map, int V, int H){
        
        if(map!=null){
            javax.swing.JPanel jPanel1= this.crear_Panel(V, H,map.getRoot().getName(), map.getWeight());
            if(map.isDirectory()){
               if(map.getChildren() !=null){
                    int n_Children = map.getChildren().size();
                    System.out.println("N_Children "+n_Children);
                    double tamnio_totalMb= map.getWeight();
                    int cont =1;
                    for (TreeMap tm: map.getChildren()){
                        
                        javax.swing.JPanel JP_sb;
                        System.out.println(tm.getRoot().getName());
                        double porc_taminio= tm.getWeight()/tamnio_totalMb;
                        
                        //cortes Verticales
                        if(cont%2==0){
                            JP_sb= this.parciones(tm,V, (int)(H*porc_taminio));
                        }else{//cortes Horizontales
                            JP_sb= this.parciones(tm,(int)(V*porc_taminio), H);
                        }
                        
                        
                        javax.swing.GroupLayout jP_sbLayout = new javax.swing.GroupLayout(JP_sb);
                        JP_sb.setLayout(jP_sbLayout);
                        jP_sbLayout.setHorizontalGroup(
                            jP_sbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGap(0, 348, Short.MAX_VALUE)
                        );
                        jP_sbLayout.setVerticalGroup(
                            jP_sbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGap(0, 487, Short.MAX_VALUE)
                        );
                    }
                }else{
                    System.out.println("Lanzar exception por hijos de mapa");
                } 
            }
        
            
        return jPanel1;    
        }else{
            System.out.println("Lanzar exception por map");
        }
        
        return null;
 
    }
    
    private javax.swing.JPanel crear_Panel(int V, int H, String nameFile, Double weight){
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        
        //crea los label de nombre de archivo y tamanio 
        javax.swing.JLabel lbl_nameFile = new javax.swing.JLabel();
        lbl_nameFile.setText(nameFile);
        javax.swing.JLabel lbl_weight_File = new javax.swing.JLabel();
        lbl_weight_File.setText(Double.toString(weight));
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);

        //add los label al Jpanel
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_nameFile, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(lbl_weight_File))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nameFile)
                    .addComponent(lbl_weight_File))
                .addGap(0, 485, Short.MAX_VALUE))
        );
        //
        
        
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, H, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, V, Short.MAX_VALUE)
        );
        return jPanel1;
    }
    
    
    private JPanel crearPanel(int V, int H, String nameFile, Double weight){
        JPanel jp= new JPanel();
        jp.setLayout(null);
        jp.setBounds(100,200,H, V);
        jp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        JLabel lbl_nameFile = new JLabel(nameFile);
        JLabel lbl_weight_File = new JLabel(Double.toString(weight)+"MB");
        jp.add(lbl_nameFile,BorderLayout.NORTH,0);
        jp.add(lbl_weight_File,BorderLayout.NORTH,-1);
        JPanel jp1= crearPanel1(V,(int)(H*(150/800)),"Archivo1",150.00);
        JPanel jp2= crearPanel1(V,(int)(H*(150/800)),"Archivo2",150.00);
        JPanel jp3= crearPanel1(V,(int)(H*(100/800)),"Archivo3",100.00);
        JPanel jpsub= crearPanel1(V,(int)(H*(400/800)),"SubDirectorio",400.00);
        JPanel jpsub1= crearPanel1((int)(V*(100/400)),(int)(H*(400/800)),"Archivo4",100.00);
        JPanel jpsub2= crearPanel1(V,(int)(H*(300/400)),"Archivo5",300.00);
        jpsub.add(jpsub1,BorderLayout.CENTER,1);
        jpsub.add(jpsub2,BorderLayout.CENTER,2);
        jp.add(jpsub,BorderLayout.CENTER,1);
        jp.add(jp1,BorderLayout.CENTER,2);
        jp.add(jp2,BorderLayout.CENTER,3);
        jp.add(jp3,BorderLayout.CENTER,4);
        
        
        return jp;
    }
    private JPanel crearPanel1(int V, int H, String nameFile, Double weight){
        JPanel jp= new JPanel();
        jp.setSize(H, V);
        jp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        JLabel lbl_nameFile = new JLabel(nameFile);
        JLabel lbl_weight_File = new JLabel(Double.toString(weight)+"MB");
        jp.add(lbl_nameFile,BorderLayout.NORTH,0);
        jp.add(lbl_weight_File,BorderLayout.NORTH,-1);
     return jp;   
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regresar;
    private javax.swing.JPanel jP2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlb_SC;
    private javax.swing.JLabel lbl_nameFile;
    private javax.swing.JLabel lbl_weight_File;
    // End of variables declaration//GEN-END:variables

}
